#!/usr/bin/env python3
"""
OSINT Syria — Quick Setup Helper
Interactive script to help set up Telegram credentials.
Run: python3 scripts/quick_setup.py
"""

import os
import sys

# Colors
G = "\033[92m"  # Green
R = "\033[91m"  # Red
Y = "\033[93m"  # Yellow
C = "\033[96m"  # Cyan
B = "\033[1m"   # Bold
D = "\033[2m"   # Dim
X = "\033[0m"   # Reset


def print_banner():
    print(f"""
{C}{B}╔══════════════════════════════════════════════════════╗
║        🇸🇾 OSINT Syria — Quick Setup Helper          ║
╚══════════════════════════════════════════════════════╝{X}
""")


def get_input(prompt, default="", secret=False):
    """Get user input with default value."""
    if secret:
        import getpass
        value = getpass.getpass(f"{C}{prompt}{X} [{D}{default[:4]}...{X}]: ").strip()
    else:
        value = input(f"{C}{prompt}{X} [{D}{default}{X}]: ").strip()
    return value if value else default


def main():
    print_banner()
    
    # Check if .env already exists
    env_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".env")
    
    if os.path.exists(env_path):
        print(f"{Y}⚠️  .env file already exists!{X}")
        overwrite = input(f"{C}Overwrite? (y/N): {X}").strip().lower()
        if overwrite != "y":
            print(f"{D}Setup cancelled.{X}")
            return
    
    print(f"{B}Step 1: Telegram API Credentials{X}")
    print(f"{D}Get these from: https://my.telegram.org → API Development Tools{X}\n")
    
    api_id = get_input("  TG_API_ID: ")
    api_hash = get_input("  TG_API_HASH: ")
    phone = get_input("  TG_PHONE_NUMBER (optional): ", "+963")
    
    print(f"\n{B}Step 2: Telegram Bot (for alerts){X}")
    print(f"{D}Create bot: Telegram → @BotFather → /newbot{X}\n")
    
    bot_token = get_input("  TG_BOT_TOKEN: ")
    chat_id = get_input("  TG_ALERT_CHAT_ID: ")
    
    print(f"\n{B}Step 3: AI Analysis (Groq - free){X}")
    print(f"{D}Get key from: https://console.groq.com{X}\n")
    
    groq_key = get_input("  GROQ_API_KEY: ")
    
    print(f"\n{B}Step 4: Database (Supabase - free){X}")
    print(f"{D}Get from: https://supabase.com → New Project{X}\n")
    
    supabase_url = get_input("  SUPABASE_URL: ", "https://your-project.supabase.co")
    supabase_key = get_input("  SUPABASE_KEY: ")
    
    # Write .env file
    env_content = f"""# OSINT Syria — Environment Configuration
# Generated by quick_setup.py

# Telegram API
TG_API_ID={api_id}
TG_API_HASH={api_hash}
TG_PHONE_NUMBER={phone}

# Telegram Bot
TG_BOT_TOKEN={bot_token}
TG_ALERT_CHAT_ID={chat_id}

# Groq AI
GROQ_API_KEY={groq_key}

# Supabase
SUPABASE_URL={supabase_url}
SUPABASE_KEY={supabase_key}

# ACLED (optional)
ACLED_KEY=

# Discord (optional)
DISCORD_WEBHOOK_URL=

# Google Drive (optional)
GDRIVE_CREDENTIALS_PATH=
"""
    
    with open(env_path, "w") as f:
        f.write(env_content)
    
    print(f"""
{G}{B}✅ .env file created successfully!{X}

{B}Next steps:{X}
  1. Test connection:  {C}python3 scripts/test_telegram.py{X}
  2. Run pipeline:     {C}python3 -m src.pipeline{X}
  3. Run dashboard:    {C}streamlit run dashboard/app.py{X}

{D}Tip: If you get "Phone code required" on first run,
     check your Telegram for the verification code.{X}
""")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print(f"\n{D}Setup cancelled.{X}")
    except Exception as e:
        print(f"\n{R}Error: {e}{X}")
        sys.exit(1)
